# Generated by Django 2.2.2 on 2019-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('Landline', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '通讯录',
            },
        ),
    ]
