# Generated by Django 2.2.2 on 2019-06-11 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syy_topics', '0005_syy_topic_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syy_entry',
            options={'verbose_name_plural': '内容'},
        ),
        migrations.AlterModelOptions(
            name='syy_topic',
            options={'verbose_name_plural': '话题'},
        ),
        migrations.AlterField(
            model_name='syy_entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
