# Generated by Django 2.2.2 on 2019-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syy_topics', '0008_syy_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syy_entry',
            options={'verbose_name_plural': '回答'},
        ),
        migrations.AlterModelOptions(
            name='syy_topic',
            options={'verbose_name_plural': '话题'},
        ),
    ]
